# Getting Started with **cleanskate**

`cleanskate` is a Python package to access clean figure skating data. Results are parsed from ISU protocols and stored on the cloud, and downloaded

The main 
To load data, import the `Dataset` handler from `cleanskate. The object supports methods for loading events, overall results, elements, and program component scores.

In [11]:
import pandas as pd

from cleanskate import Dataset

ds = Dataset()

events = ds.load_events()
results = ds.load_results()
segments = ds.load_segments()
elements = ds.load_elements()
components = ds.load_program_components()

print(f'Events: {len(events)}')
print(f'Segments: {len(segments)}')
print(f'Results: {len(results)}')
print(f'Participants: {len(results["name"].unique())}')
print(f'Elements: {len(elements)}')

Events: 51
Segments: 424
Results: 8286
Participants: 1364
Elements: 70290

## Skater performance on specific elements

In [4]:
# calculate different skaters performance on a particular element
ELEMENT = '4T+3T'
elements_subset = elements[ elements['element_code'].str.startswith(ELEMENT) ]
skater_scores_on_element = elements_subset.groupby('name', as_index=False).agg(
    count=('goe', len),
    mean_goe=('goe', lambda x: sum(x)/len(x)),
    prob_clean=('info_flags', lambda x: sum(pd.isna(x))/len(x))
    )

skater_scores_on_element[ skater_scores_on_element['count'] >= 5].sort_values(by='mean_goe', ascending=False)

                   name  count  mean_goe  prob_clean
46        Yuma KAGIYAMA     14  3.567857    1.000000
47         Yuzuru HANYU      6  3.098333    1.000000
19       Keegan MESSING      5  2.580000    1.000000
39        Sota YAMAMOTO      6  2.440000    1.000000
13         Ilia MALININ      7  2.404286    1.000000
38            Shun SATO     12  2.393333    1.000000
17            Kao MIURA      8  1.977500    1.000000
43  Vladimir LITVINTSEV      7  1.765714    1.000000
42     Tomoki HIWATASHI      6  1.720000    1.000000
29    Mikhail SHAIDOROV     13  1.650000    1.000000
40      Stephen GOGOLEV      5  1.634000    1.000000
20          Kevin AYMOZ      9  1.633333    1.000000
18        Kazuki TOMONO      9  1.335556    1.000000
0      Adam SIAO HIM FA     14  1.320714    0.928571
24      Lukas BRITSCHGI      8  1.142500    1.000000
11  Gabriele FRANGIPANI      5  0.950000    0.800000
12    Georgii RESHTENKO      6  0.910000    0.833333

In [5]:
ilia_elements = elements[ elements['name'] == 'Ilia MALININ' ]
jump_counts = ilia_elements[ ilia_elements['element_family'].str.contains('Jump') ].groupby(['element_family', 'element_code'], as_index=False).size().sort_values(by='size', ascending=False)
jump_counts

   element_family element_code  size
4            Jump           3A    20
11           Jump           4F    15
14           Jump          4Lz    11
34     Jump Combo        4T+3T     7
25     Jump Combo       4Lz+3T     7
39  Jump Sequence    4S+3A+SEQ     6
7            Jump          3Lo     5
18           Jump           4T     5
23     Jump Combo       3Lz+3T     4
13           Jump          4Lo     4
24     Jump Combo   4Lz+1Eu+3F     3
16           Jump           4S     3
9            Jump           4A     3
31     Jump Combo     4Lzq+REP     2
32     Jump Combo    4T+1Eu+3F     2
37  Jump Sequence   3Lz+3A+SEQ     2
30     Jump Combo      4Lzq+3T     2
0            Jump           1A     2
20     Jump Combo        3F+3T     2
8            Jump          3Lz     2
15           Jump         4Lzq     2
10           Jump          4Aq     2
5            Jump           3F     2
38  Jump Sequence    4S+2A+SEQ     1
2            Jump          2Lz     1
36     Jump Combo   4Tq+1Eu+3F     1
35     Jump Combo     4T<<+REP     1
3            Jump           2S     1
33     Jump Combo    4T+1Eu+3S     1
6            Jump          3F<     1
17           Jump         4S<<     1
19     Jump Combo        3A+2T     1
28     Jump Combo  4Lzq+1Eu+3F     1
27     Jump Combo      4Lz<+3T     1
26     Jump Combo  4Lz<+1Eu+3S     1
12           Jump          4Fq     1
22     Jump Combo   3Lz+1Eu+3S     1
21     Jump Combo  3Lz*+1Eu+3S     1
1            Jump          2Lo     1
29     Jump Combo  4Lzq+1Eu+3S     1

In [8]:
ilia_elements[['event_label', 'segment_label']].drop_duplicates()

                              event_label  segment_label
4358             CS Lombardia Trophy 2025         Men SP
4470             CS Lombardia Trophy 2025         Men FS
27123  GP Skate Canada International 2025         Men SP
27207  GP Skate Canada International 2025         Men FS
28583               Grand Prix Final 2025         Men SP
28611               Grand Prix Final 2025         Men FS
30093        GP Grand Prix de France 2025         Men SP
30177        GP Grand Prix de France 2025         Men FS
44286                       Olympics 2026         Men SP
44657                       Olympics 2026         Men FS
45883                       Olympics 2026    Team Men SP
45946                       Olympics 2026    Team Men FS
49873                         Worlds 2022         Men SP
50175                         Worlds 2022         Men FS
51418                         Worlds 2023         Men SP
51673                         Worlds 2023         Men FS
53073                         Worlds 2024         Men SP
53339                         Worlds 2024         Men FS
54913                         Worlds 2025         Men SP
55186                         Worlds 2025         Men FS
56740                         Worlds 2026         Men SP
56992                         Worlds 2026         Men FS
60283                  Junior Worlds 2020  Junior Men SP
60624                  Junior Worlds 2020  Junior Men FS
61869                  Junior Worlds 2022  Junior Men SP
62100                  Junior Worlds 2022  Junior Men FS

In [ ]:
## Components